=== mayametodieva/XML-FMI-2023/serious-video-games.dtd
<!ELEMENT catalogue (genres,sectors,games)>
<!ELEMENT genres (genre+)>
<!ELEMENT genre (image,description)>
<!ATTLIST genre
        id    ID     #REQUIRED
        title CDATA  #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image EMPTY>

<!ELEMENT sectors (sector+)>
<!ELEMENT sector (image,description)>
<!ATTLIST sector
        id    ID    #REQUIRED
        title CDATA #REQUIRED>

<!ELEMENT games (game*)>
<!ELEMENT game (description,about,requirements,gallery)>
<!ATTLIST game  id    ID    #REQUIRED
                title CDATA #REQUIRED>

<!NOTATION JPEG SYSTEM "image/jpg">
<!NOTATION PNG  SYSTEM "image/png">   

<!ENTITY civilization_VI_logo SYSTEM "images/game_logos/civilization_VI_logo.png"  NDATA PNG>
<!ENTITY FIFA_23_logo         SYSTEM "images/game_logos/FIFA_23_logo.png"  NDATA PNG>
<!ENTITY vs_ed_logo           SYSTEM "images/game_logos/vs_ed_logo.png"  NDATA PNG>
<!ENTITY minecraft_logo       SYSTEM "images/game_logos/minecraft_logo.png"  NDATA PNG>
<!ENTITY call_of_duty_logo    SYSTEM "images/game_logos/call_of_duty_logo.png"   NDATA PNG>
<!ENTITY take_on_mars_logo    SYSTEM "images/game_logos/take_on_mars_logo.png"   NDATA PNG>
<!ENTITY wow_logo             SYSTEM "images/game_logos/wow_logo.png"  NDATA PNG>  

<!ENTITY call_of_duty1        SYSTEM "images/gallery/call_of_duty1.png"      NDATA PNG>  
<!ENTITY call_of_duty2        SYSTEM "images/gallery/call_of_duty2.png"      NDATA PNG>  
<!ENTITY call_of_duty3        SYSTEM "images/gallery/call_of_duty3.png"      NDATA PNG>  
<!ENTITY call_of_duty4        SYSTEM "images/gallery/call_of_duty4.png"      NDATA PNG>  
<!ENTITY civilization_VI_1    SYSTEM "images/gallery/civilization_VI_1.png"  NDATA PNG>  
<!ENTITY civilization_VI_2    SYSTEM "images/gallery/civilization_VI_2.png"  NDATA PNG>  
<!ENTITY civilization_VI_3    SYSTEM "images/gallery/civilization_VI_3.png"  NDATA PNG>  
<!ENTITY civilization_VI_4    SYSTEM "images/gallery/civilization_VI_4.png"  NDATA PNG>  
<!ENTITY fifa1                SYSTEM "images/gallery/fifa1.png"              NDATA PNG>  
<!ENTITY fifa2                SYSTEM "images/gallery/fifa2.png"              NDATA PNG>  
<!ENTITY fifa3                SYSTEM "images/gallery/fifa3.png"              NDATA PNG>  
<!ENTITY fifa4                SYSTEM "images/gallery/fifa4.png"              NDATA PNG> 
<!ENTITY minecraft1           SYSTEM "images/gallery/minecraft1.png"         NDATA PNG> 
<!ENTITY minecraft2           SYSTEM "images/gallery/minecraft2.png"         NDATA PNG> 
<!ENTITY minecraft3           SYSTEM "images/gallery/minecraft3.png"         NDATA PNG> 
<!ENTITY minecraft4           SYSTEM "images/gallery/minecraft4.png"         NDATA PNG> 
<!ENTITY take_on_mars_1       SYSTEM "images/gallery/take_on_mars_1.png"     NDATA PNG> 
<!ENTITY take_on_mars_2       SYSTEM "images/gallery/take_on_mars_2.png"     NDATA PNG> 
<!ENTITY take_on_mars_3       SYSTEM "images/gallery/take_on_mars_3.png"     NDATA PNG> 
<!ENTITY take_on_mars_4       SYSTEM "images/gallery/take_on_mars_4.png"     NDATA PNG> 
<!ENTITY vital_signs_1        SYSTEM "images/gallery/vital_signs_1.png"      NDATA PNG> 
<!ENTITY vital_signs_2        SYSTEM "images/gallery/vital_signs_2.png"      NDATA PNG> 
<!ENTITY vital_signs_3        SYSTEM "images/gallery/vital_signs_3.png"      NDATA PNG> 
<!ENTITY vital_signs_4        SYSTEM "images/gallery/vital_signs_4.png"      NDATA PNG> 
<!ENTITY wow1                 SYSTEM "images/gallery/wow1.png"               NDATA PNG> 
<!ENTITY wow2                 SYSTEM "images/gallery/wow2.png"               NDATA PNG> 
<!ENTITY wow3                 SYSTEM "images/gallery/wow3.png"               NDATA PNG> 
<!ENTITY wow4                 SYSTEM "images/gallery/wow4.png"               NDATA PNG> 

<!ENTITY advergames_title     SYSTEM "images/titles/advergames_title.png"    NDATA PNG> 
<!ENTITY education_title      SYSTEM "images/titles/education_title.png"     NDATA PNG> 
<!ENTITY health_title         SYSTEM "images/titles/health_title.png"        NDATA PNG> 
<!ENTITY production_title     SYSTEM "images/titles/production_title.png"    NDATA PNG> 
<!ENTITY science_title        SYSTEM "images/titles/science_title.png"       NDATA PNG> 
<!ENTITY training_title       SYSTEM "images/titles/training_title.png"      NDATA PNG> 
<!ENTITY work_title           SYSTEM "images/titles/work_title.png"          NDATA PNG> 

<!ENTITY corporate_sector     SYSTEM "images/sectors/corporate_sector.png"   NDATA PNG> 
<!ENTITY defense_sector       SYSTEM "images/sectors/defense_sector.png"     NDATA PNG> 
<!ENTITY education_sector     SYSTEM "images/sectors/education_sector.png"   NDATA PNG> 
<!ENTITY government_sector    SYSTEM "images/sectors/government_sector.png"  NDATA PNG> 
<!ENTITY healtchcare_sector   SYSTEM "images/sectors/healtchcare_sector.png" NDATA PNG> 
<!ENTITY industry_sector      SYSTEM "images/sectors/industry_sector.png"    NDATA PNG> 
<!ENTITY marketing_sector     SYSTEM "images/sectors/marketing_sector.png"   NDATA PNG>


<!ENTITY % ratings "    everyone            |
                        everyone_10_plus    |
                        teen                |
                        mature_17_plus      |
                        adults_only         ">

<!ELEMENT about (supportedLanguages)>
<!ATTLIST about genres          IDREFS      #REQUIRED
                sectors         IDREFS      #REQUIRED
                logo            ENTITY      #REQUIRED
                website         CDATA       #REQUIRED
                releaseDate     CDATA       #REQUIRED
                contentRating   (%ratings;) #REQUIRED>
                
<!ELEMENT supportedLanguages (#PCDATA)>
<!ELEMENT requirements (minimum,recommended)>
<!ELEMENT minimum (os,processor,memory,graphics,storage)>
<!ELEMENT os (#PCDATA)>
<!ELEMENT processor (#PCDATA)>
<!ELEMENT memory (#PCDATA)>
<!ELEMENT graphics (#PCDATA)>
<!ELEMENT storage (#PCDATA)>
<!ELEMENT recommended (os,processor,memory,graphics,storage)>
<!ELEMENT gallery (image+)>
<!ATTLIST image
        source CDATA #REQUIRED>

=== mayametodieva/XML-FMI-2023/serious-video-games.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "serious-video-games.xsl"?>

<!DOCTYPE catalogue SYSTEM "serious-video-games.dtd">

<catalogue>
  <genres>
    <genre id="gr-0001" title="Games for Health" >
      <image source="health_title"/>
      <description>
        Games for Health are games that aim to either promote 
        health or to prevent, diagnose or treat (chronic) diseases. 
        These games, which are generally considered serious games, 
        aim to influence health outcomes by increasing the user's 
        knowledge and changing their behaviors through play.
      </description>
    </genre>
    <genre id="gr-0002" title="Advergames">
      <image source="advergames_title"/>
      <description>
        An advergame is a form of advertising in video games, 
        in which the video game is developed by or in close 
        collaboration with a corporate entity for purposes of 
        advertising a brand-name product. While other video games 
        may use in-game advertising (such as an advertisement 
        on a virtual billboard or branding on an in-game object), 
        an advergame is differentiated by the Interactive 
        Advertising Bureau as a "game specifically designed 
        around product or service being advertised". 
      </description>
    </genre>
    <genre id="gr-0003" title="Games for Training">
      <image source="training_title"/>
      <description>
        Games for training, also known as serious 
        games or edutainment games, are video games 
        that are designed to educate or train players 
        in a specific subject or skill. These games are 
        often used in education, corporate training, and 
        military training, and can be used to teach a wide 
        variety of topics, such as leadership, teamwork, 
        problem-solving, and technical skills. Games for 
        training can be effective at engaging and motivating 
        learners, and can be used to supplement traditional 
        teaching methods or to create immersive, interactive 
        learning experiences.
      </description>
    </genre>
    <genre id="gr-0004" title="Games for Education">
      <image source="education_title"/>
      <description>
        Educational games are games explicitly designed with 
        educational purposes, or which have incidental or 
        secondary educational value. All types of games may 
        be used in an educational environment, however 
        educational games are games that are designed to 
        help people learn about certain subjects, expand 
        concepts, reinforce development, understand a historical 
        event or culture, or assist them in learning a skill 
        as they play. Game types include board, card, and 
        video games.
      </description>
    </genre>
    <genre id="gr-0005" title="Games for Science and Research">
      <image source="science_title"/>
      <description>
        Games for science and research often have a specific scientific or research-related goal,
        such as mapping the brain, collecting data on spatial navigation,
        or identifying patterns in DNA sequences. Games for science and 
        research can be used to engage the general public in scientific 
        research, to collect data that would be difficult or impossible 
        to gather through traditional means, or to help researchers understand 
        complex systems or solve problems. These games can be an effective way 
        to promote scientific literacy and encourage people to learn about and 
        contribute to scientific research.
      </description>
    </genre>
    <genre id="gr-0006" title="Production">
      <image source="production_title"/>
      <description>
        Games for production, also known as factory simulation games
        or tycoon games, are video games that simulate the management
        and operation of a production facility. These games often involve
        tasks such as gathering resources, building structures and machines,
        and automating production processes in order to create a product or 
        service. Games for production can be used to teach players about
        various aspects of production, such as supply chain management,
        resource allocation, and quality control. These games can also
        be used to challenge players to find the most efficient and
        effective ways to produce goods or services.
      </description>
    </genre>
    <genre id="gr-0007" title="Games as Work">
      <image source="work_title"/>
      <description>
        Games for work, also known as gamification or gamified training,
        are video games or game-like elements that are used to engage 
        and motivate employees in their work. These games can be used 
        to teach new skills, encourage teamwork and collaboration, 
        or improve productivity. Games for work can be incorporated 
        into training programs, used as part of a rewards or recognition system, 
        or implemented as part of a company's culture and values. Gamification 
        can be an effective way to engage and motivate employees, and can be 
        used in a variety of industries and settings.
      </description>
    </genre>
  </genres>
  <sectors>
    <sector id="sr-0001" title="Government &amp; NGO">
      <image source="government_sector"/>
      <description>
        A government and NGO serious game is a type of simulation game that is used by government 
        agencies and non-governmental organizations (NGOs) to train employees, educate the public, and solve problems. 

        These games can be used to train employees in a variety of skills, such as leadership, 
        teamwork, and problem-solving. They can also be used to educate the public about a particular issue, or to 
        explore different approaches to solving problems.

        Government and NGO serious games can be played on a computer, or they can be played in a physical setting. 

        Overall, government and NGO serious games are an important tool for these organizations to train and prepare 
        employees, and to educate the public and explore new approaches to solving problems.
      </description>
    </sector>
    <sector id="sr-0002" title="Defense">
      <image source="defense_sector"/>
      <description>
        A defense serious game is a type of simulation game that is used by military and 
        defense organizations to train personnel, plan strategies, and test new equipment.

        These games can be used to train personnel in a variety of skills, including 
        combat tactics, leadership, and decision-making. They can also be used to test new 
        equipment or to explore different strategies and scenarios.

        Defense serious games can be played on a computer, or they can be played in a physical
        setting with simulated equipment. 

        Overall, defense serious games are an important tool for military and defense organizations
        to train and prepare personnel for a wide range of real-world situations.
      </description>
    </sector>
    <sector id="sr-0003" title="Healthcare">
      <image source="healtchcare_sector"/>
      <description>
        A healthcare serious game is a type of simulation game that is used in the healthcare 
        industry to train professionals, educate the public, and explore different treatment options.
        
        These games can be used to train professionals in a variety of skills,
        including patient care, diagnosis, and treatment. They can also be used to educate
        the public about health issues or to explore different treatment options.

        Healthcare serious games can be played on a computer, or they can be played
        in a physical setting with simulated equipment. 

        Overall, healthcare serious games are an important tool for the healthcare industry to train and prepare 
        professionals and to explore new treatment options.
      </description>
    </sector>
    <sector id="sr-0004" title="Marketing &amp; Communications">
      <image source="marketing_sector"/>
      <description>
        A marketing and communications serious game is a type of simulation 
        game that is used by organizations to train employees in marketing
        and communications skills, and to explore different marketing and 
        communication strategies. 

        Marketing and communications serious games can be used to train employees 
        in a variety of skills, including sales, advertising, and public relations. 
        They can also be used to explore different marketing and communication strategies, 
        and to test the effectiveness of different messages and campaigns.

        Marketing and communications serious games can be played on a computer, 
        or they can be played in a physical setting. 

        Overall, marketing and communications serious games are an important tool for organizations to 
        train and prepare employees in marketing and communication skills, and to explore new strategies.
      </description>
    </sector>
    <sector id="sr-0005" title="Education">
      <image source="education_sector"/>
      <description>
        An education serious game is a type of game that is designed to teach players about
        a particular subject or issue in an interactive and engaging way. These games 
        are often used in formal education settings, such as schools and universities, 
        as well as in other settings, such as museums and science centers.

        Education serious games can cover a wide range of subjects, from math and science
